Project1/objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <label>Event</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/objects/Expense_Member__c.object
<CustomObject>
    <fields>
        <fullName>Contribution_Amount_INR__c</fullName>
        <label>Contribution Amount (INR)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expense__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Expense Members</relationshipLabel>
        <relationshipName>Expense_Members</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Expense Member</label>
    <nameField>
        <displayFormat>ExpMemId - {00000}</displayFormat>
        <label>Expense_Member_Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project1/objects/Member__c.object
<CustomObject>
    <label>Member</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1/classes/ExpenseEXT.cls
public with sharing class ExpenseEXT                                                                                        // class declaration
{
    public Expense__c expObj{get;set;}                                                                                      // object of Expense_c type
    public List<Expense_Member__c> memExp{get;set;}                                                                         // object of array-list return type

    public ExpenseEXT(ApexPages.StandardController controller)                                                              // class constructor
    {
        expObj = (Expense__c)controller.getRecord();                                                                   
        memExp = getExpMembers();
    }
    
    public List<Expense_Member__c> getExpMembers()                                                                          // returns list records of Expense_Members oject                                    
    {
        return [Select Member__r.Name, Contribution_Amount_INR__c from Expense_Member__c where Expense__c =: expObj.Id];
    }
}